version: '2.3'

services:
  app:
    tty: true # need along with up -d otherwise container exits
    build: .
    container_name: cuda-llama-chat
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              